### ISSUE TITLE
$box-shadow/$color special rule

### ISSUE THREAD

**Issue by silverwind** [silverwind/remap-css#4]
To catch stuff like `box-shadow: inset 1px 0 0 #fff;`

**Comment by the-j0k3r** [comment]
Why isnt https://github.com/StylishThemes/GitHub-Dark/commit/a8763f969d2a684c1f50a363352a0a4a3dc66c93 the right way that you need further resolution?

OK I see you mean like the existing $border, $background things... ya :)

**Comment by silverwind** [comment]
Yes, like `$background`. It should go off the color and create a appropriate rule. Box shadows are a bit tricky thought as there can be multiple etc.

**Comment by the-j0k3r** [comment]
$border can be multiple also, and that logic seems to work OK.

**Comment by silverwind** [comment]
I mean CSS syntax allows multiple comma-separated values for `box-shadow`, but not `border`.

**Comment by the-j0k3r** [comment]
Ah yes... I see the complication

**Comment by silverwind** [comment]
Added in https://github.com/silverwind/remap-css/commit/7d81cc210c432897224b84444e7026a992719361.
